import { useMemo, useState } from "react";
import { ArrowLeft, BookOpen, Moon, Search, Sun } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useTheme } from "@/contexts/ThemeContext";

type GlossaryItem = { term: string; category: string; meaning: string; reading: string; caution: string };

const glossary: GlossaryItem[] = [
  { term: "EMA", category: "Xu hướng", meaning: "Exponential Moving Average là đường trung bình động ưu tiên dữ liệu gần nhất.", reading: "Giá nằm trên EMA và EMA ngắn nằm trên EMA dài thường ủng hộ xu hướng tăng; ngược lại ủng hộ xu hướng giảm.", caution: "EMA có độ trễ và nên được xác nhận bằng cấu trúc giá, volume hoặc khung lớn hơn." },
  { term: "MACD", category: "Động lượng", meaning: "Moving Average Convergence Divergence đo quan hệ giữa hai EMA và đường tín hiệu.", reading: "MACD cắt lên đường tín hiệu hoặc histogram dương cho thấy động lượng tăng đang cải thiện; tín hiệu ngược lại cho động lượng giảm.", caution: "MACD dễ nhiễu khi thị trường đi ngang; không nên dùng như tín hiệu vào lệnh độc lập." },
  { term: "RSI", category: "Động lượng", meaning: "Relative Strength Index đo động lượng trong khoảng 0–100.", reading: "Trên 70 thường được xem là quá mua và dưới 30 là quá bán, nhưng trong xu hướng mạnh RSI có thể duy trì ở vùng cực trị.", caution: "Quá mua không đồng nghĩa phải bán ngay; hãy đối chiếu xu hướng và vùng giá." },
  { term: "ADX", category: "Xu hướng", meaning: "Average Directional Index đo độ mạnh của xu hướng, không xác định hướng tăng hay giảm.", reading: "ADX cao thường cho thấy xu hướng rõ hơn; ADX thấp thường phản ánh thị trường đi ngang.", caution: "Cần xem thêm DI+/DI− hoặc nhãn xu hướng để biết hướng di chuyển." },
  { term: "ATR", category: "Biến động", meaning: "Average True Range đo biên độ biến động trung bình theo đơn vị giá.", reading: "ATR cao cho thấy biến động lớn hơn và khoảng SL/TP cần được cân nhắc rộng hơn.", caution: "ATR không dự đoán hướng và không nên được hiểu là giá sẽ đi đúng bằng ATR." },
  { term: "Volume ratio", category: "Thanh khoản", meaning: "Tỷ lệ volume nến hiện tại so với volume trung bình của cửa sổ phân tích.", reading: "x1.00 là ngang trung bình; tỷ lệ cao hơn cho thấy hoạt động giao dịch tăng.", caution: "Volume lớn không tự xác nhận tăng hay giảm; cần kết hợp hướng nến và cấu trúc giá." },
  { term: "Trend score", category: "Tổng hợp", meaning: "Điểm 0–100 của engine, tổng hợp hướng EMA, động lượng, RSI, ADX, volume và cấu trúc giá.", reading: "Điểm dương nghiêng Bullish, âm nghiêng Bearish; độ lớn thể hiện mức đồng thuận của tín hiệu.", caution: "Đây là điểm xếp hạng tương đối, không phải xác suất lợi nhuận." },
  { term: "Risk score", category: "Rủi ro", meaning: "Điểm 0–100 phản ánh độ bất định, biến động, chất lượng volume và khoảng cách đến SL.", reading: "Điểm càng cao nghĩa là điều kiện giao dịch càng bất định hoặc biên độ rủi ro càng lớn.", caution: "Risk score không thay thế quản trị vốn và không phải lời khuyên đầu tư." },
  { term: "Confidence", category: "Tổng hợp", meaning: "Mức độ tin cậy giải thích được của tín hiệu, có hiệu chỉnh theo dữ liệu outcome đã giải quyết.", reading: "Confidence cao hơn nghĩa là các điều kiện hỗ trợ nhất quán hơn trong dữ liệu hiện tại.", caution: "Khi số mẫu lịch sử ít, confidence được co về mức thận trọng và không phải xác suất." },
  { term: "Multi-timeframe", category: "Xác nhận", meaning: "Đối chiếu tín hiệu giữa 15m, 1h, 4h và 1d để giảm tín hiệu nhiễu.", reading: "Tín hiệu ngắn hạn được ưu tiên khi không xung đột với khung lớn hơn theo quy tắc engine.", caution: "Thiếu dữ liệu khung lớn hoặc xung đột có thể dẫn tới No Trade." },
  { term: "Entry", category: "Mức giá", meaning: "Vùng giá tham chiếu để cân nhắc mở vị thế theo phân tích hiện tại.", reading: "Entry được tính từ giá và biến động của snapshot, không phải lệnh đã được đặt.", caution: "Giá thị trường có thể thay đổi; cần kiểm tra spread và thanh khoản trước hành động." },
  { term: "Take Profit (TP1/TP2)", category: "Mức giá", meaning: "Các mốc giá mục tiêu dùng để đánh giá kịch bản có lợi.", reading: "TP1 thường là mục tiêu gần hơn; TP2 là mục tiêu xa hơn trong cùng kịch bản.", caution: "Mục tiêu không đảm bảo sẽ đạt và phải được xem cùng tỷ lệ risk/reward." },
  { term: "Stop Loss (SL)", category: "Mức giá", meaning: "Mốc giá dùng để xác định kịch bản không còn hợp lệ hoặc giới hạn thua lỗ dự kiến.", reading: "Khoảng Entry–SL là cơ sở để ước tính rủi ro mỗi giao dịch.", caution: "SL có thể trượt trong thị trường biến động hoặc thanh khoản thấp." },
  { term: "No Trade", category: "Quyết định", meaning: "Trạng thái engine không khuyến nghị giao dịch vì tín hiệu yếu, xung đột hoặc thiếu xác nhận.", reading: "Snapshot vẫn được lưu để theo dõi, nhưng có thể bị chặn khỏi chế độ Strong Only.", caution: "No Trade không dự đoán chắc chắn giá sẽ đi ngang hay đảo chiều." },
  { term: "Hit rate", category: "Backtest", meaning: "Tỷ lệ outcome TP/SL đã giải quyết có kết quả thắng.", reading: "Chỉ tính trên mẫu đã giải quyết; outcome expired được báo riêng.", caution: "Hit rate không thể hiện quy mô lãi/lỗ hoặc chi phí giao dịch." },
  { term: "Expectancy", category: "Backtest", meaning: "Lợi nhuận kỳ vọng trung bình của các outcome đã giải quyết.", reading: "Expectancy dương là trung bình mẫu có lợi nhuận; âm là ngược lại.", caution: "Mẫu nhỏ có thể biến động mạnh và không đại diện cho tương lai." },
  { term: "Maximum drawdown", category: "Backtest", meaning: "Mức sụt giảm lớn nhất từ đỉnh vốn giả định xuống đáy tiếp theo trong chuỗi kết quả.", reading: "Giá trị tuyệt đối càng lớn cho thấy chuỗi kết quả có giai đoạn suy giảm sâu hơn.", caution: "Backtest không bao gồm mọi chi phí, trượt giá hoặc giới hạn thực thi." },
  { term: "Horizon P&L", category: "Backtest", meaning: "Biến động mark-to-market tại cuối horizon khi TP/SL chưa chạm.", reading: "Được hiển thị riêng với hit rate và expectancy để không biến outcome chưa giải quyết thành chiến thắng/thua cuộc.", caution: "Đây là giá trị tham chiếu theo cửa sổ quan sát, không phải outcome đã đóng." },
];

export default function Glossary() {
  const { theme, toggleTheme } = useTheme();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Tất cả");
  const categories = ["Tất cả", ...Array.from(new Set(glossary.map(item => item.category)))];
  const filtered = useMemo(() => glossary.filter(item => (category === "Tất cả" || item.category === category) && `${item.term} ${item.meaning} ${item.reading}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <main className="min-h-screen bg-background px-4 py-6 text-foreground md:px-8"><div className="mx-auto max-w-7xl"><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Reference Library</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-semibold"><BookOpen className="h-7 w-7 text-primary" />Từ điển thuật ngữ kỹ thuật</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Giải thích các chỉ số, mức giá, trạng thái tín hiệu và metric Backtest trong Crypto Trend Signal.</p></div><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={toggleTheme} aria-label={theme === "dark" ? "Bật light mode" : "Bật dark mode"}>{theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</Button><Button variant="outline" onClick={() => { window.location.href = "/"; }}><ArrowLeft className="mr-2 h-4 w-4" />Dashboard</Button></div></header><Card className="mb-5"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Tìm RSI, Entry, drawdown..." className="pl-9" aria-label="Tìm thuật ngữ" /></label><select value={category} onChange={event => setCategory(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm text-foreground" aria-label="Lọc theo nhóm">{categories.map(item => <option key={item}>{item}</option>)}</select></CardContent></Card><p className="mb-3 text-xs text-muted-foreground">Hiển thị {filtered.length}/{glossary.length} thuật ngữ · Nội dung mang tính giáo dục, không phải khuyến nghị đầu tư.</p><div className="grid gap-4 md:grid-cols-2">{filtered.map(item => <Card key={item.term} className="border-border bg-card transition-shadow hover:shadow-lg"><CardHeader className="pb-2"><div className="flex items-center justify-between gap-3"><CardTitle className="text-base">{item.term}</CardTitle><span className="rounded-full border border-primary/20 bg-primary/5 px-2 py-1 text-[10px] font-medium text-primary">{item.category}</span></div></CardHeader><CardContent className="space-y-3 text-sm"><p className="leading-6 text-foreground/85">{item.meaning}</p><div className="rounded-lg border border-border bg-muted/40 p-3 text-xs leading-5"><strong className="text-foreground">Cách đọc:</strong> <span className="text-muted-foreground">{item.reading}</span></div><p className="text-xs leading-5 text-muted-foreground"><strong className="text-foreground">Lưu ý:</strong> {item.caution}</p></CardContent></Card>)}</div>{filtered.length === 0 && <Card className="py-12 text-center"><CardContent className="text-sm text-muted-foreground">Không tìm thấy thuật ngữ phù hợp.</CardContent></Card>}</div></main>;
}
